[application]

# App (Project) Name
name = "landing"
out_dir = "docs"

[web.app]

# HTML title tag content
title = "landing"
base_path = "web"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
